version: "3.9"
services:
  app:
    build: .
    ports:
      - 7000:3000
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "erman"
      MONGO_INITDB_ROOT_PASSWORD: "erman"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8000:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "erman"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "erman"

volumes:
  mongo-data:
